//erro const
const a = 10
a = 20 //quebra aqui
console.log(a)//não roda a partir daqui
//se usar o try catch é possivel retornar linha 6
console.log("tchau")
